name: rxnemb
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - networkx==3.3
  - numpy==1.26.4
  - pyg-lib==0.4.0+pt22cu121
  - python-box==7.3.2
  - rdkit==2024.3.2
  - scikit-learn==1.7.2
  - tensorboard==2.20.0
  - torch==2.2.1+cu121
  - torch-geometric==2.6.1
  - torch_cluster==1.6.3+pt22cu121
  - torch_scatter==2.1.2+pt22cu121
  - torch_sparse==0.6.18+pt22cu121
  - torch_spline_conv==1.2.2+pt22cu121
  - torchdata==0.7.1
  - torchtext==0.4.0
  - tqdm==4.67.1
  - pandas==2.3.3
  - seaborn==0.13.2
  - jupyterlab
