name: rxnemb
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy==1.26.4
  - rdkit==2024.3.2
  - scikit-learn==1.7.2
  - torch==2.2.1+cu121
  - torch-geometric==2.6.1
  - tqdm==4.67.1
  - pandas==2.3.3
  - seaborn==0.13.2
  - jupyterlab
